spring.application.name=myfirstProject

# MongoDB
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/myfirstProject

# Show detailed Spring Boot logs
logging.level.org.springframework=DEBUG

# Show MongoDB logs
logging.level.org.springframework.data.mongodb=DEBUG

# Show MongoDB driver logs
logging.level.org.mongodb.driver=DEBUG